#!/usr/bin/env bash

set -e

echo "Beginning resource build . . ."

rm -rf dev-res-* stable-res-*

./get-dev-resources \
    && ./get-stable-resources \
    && ./get-wareya-shaders \
    && ./get-wareya-pbr