#!/usr/bin/env bash

set -e

url="https://github.com/wareya/OpenMW-PBR/archive/refs/heads/main.zip"

wget -q --show-progress -O "wareya-pbr.zip" "${url}"
unzip wareya-pbr.zip

mv OpenMW-PBR-main/AUTHORS.md OpenMW-PBR-main/PBR-AUTHORS.md
mv OpenMW-PBR-main/LICENSE OpenMW-PBR-main/PBR-LICENSE
mv OpenMW-PBR-main/README.md OpenMW-PBR-main/PBR-README.md

cp -r ./dev-res-wareyaWater ./dev-res-NOPBR-wareyaWater
cp -r ./dev-res-vanillaWater ./dev-res-NOPBR-vanillaWater

cp -r ./stable-res-wareyaWater ./stable-res-NOPBR-wareyaWater
cp -r ./stable-res-vanillaWater ./stable-res-NOPBR-vanillaWater

cp -r OpenMW-PBR-main/* ./dev-res-wareyaWater/resources
cp -r OpenMW-PBR-main/* ./dev-res-vanillaWater/resources

cp -r OpenMW-PBR-main/* ./stable-res-wareyaWater/resources
cp -r OpenMW-PBR-main/* ./stable-res-vanillaWater/resources

mv stable-res-vanillaWater stable-res-PBR-vanillaWater
mv stable-res-wareyaWater stable-res-PBR-wareyaWater

mv dev-res-vanillaWater dev-res-PBR-vanillaWater
mv dev-res-wareyaWater dev-res-PBR-wareyaWater

rm -r wareya-pbr.zip OpenMW-PBR-main
