#!/usr/bin/env bash

set -e

echo "Retrieving Wareya shaders . . ."

url="https://github.com/wareya/OpenMW-Shaders/archive/refs/heads/main.zip"

wget -q --show-progress -O "wareya-shaders.zip" "${url}"
unzip wareya-shaders.zip && rm wareya-shaders.zip
cd OpenMW-Shaders-main

mv LICENSE war-shad-LICENSE
mv README.md war-shad-README.md

mv EXPERIMENTS/* shaders
rm -r EXPERIMENTS

cp -r war-shad-LICENSE war-shad-README.md shaders ../dev-res/resources/vfs
cp -r war-shad-LICENSE war-shad-README.md shaders ../stable-res/resources/vfs

cd -
rm -r OpenMW-Shaders-main

cp -r dev-res dev-res-vanilla-water
cp -r stable-res stable-res-vanilla-water

# For variants which do not have the appropriate edits to use the water shader, remove them for deployment
cd stable-res-vanilla-water/shaders/
rm water.omwfx waterLite.omwfx waterLite2.omwfx waterNew.omwfx waterUltraLite.omwfx
cd - && cd dev-res-vanilla-water/shaders
rm water.omwfx waterLite.omwfx waterLite2.omwfx waterNew.omwfx waterUltraLite.omwfx
cd -

awk '/gl_FragData\[0\] = applyFogAtDist\(/ {
    print $0
    print "    gl_FragData[0] = vec4(0.0);"
    next
} 1' stable-res/resources/shaders/compatibility/water.frag > tmpfile && mv tmpfile stable-res/resources/shaders/compatibility/water.frag

awk '/gl_FragData\[0\] = applyFogAtDist\(/ {
    print $0
    print "    gl_FragData[0] = vec4(0.0);"
    next
} 1' dev-res/resources/shaders/compatibility/water.frag > tmpfile && mv tmpfile dev-res/resources/shaders/compatibility/water.frag

mv stable-res stable-res-war-water
mv dev-res dev-res-war-water
