#!/usr/bin/env bash

set -e

echo "Retrieving Wareya shaders . . ."

url="https://github.com/wareya/OpenMW-Shaders/archive/refs/heads/main.zip"

wget -q --show-progress -O "wareya-shaders.zip" "${url}"
unzip wareya-shaders.zip
cd OpenMW-Shaders-main

mv LICENSE war-shad-LICENSE
mv README.md war-shad-README.md

mv EXPERIMENTS/* shaders
rm -r EXPERIMENTS

cp -r war-shad-LICENSE war-shad-README.md shaders ../dev-res/resources/vfs
cp -r war-shad-LICENSE war-shad-README.md shaders ../stable-res/resources/vfs

cd -
rm -r OpenMW-Shaders-main

cp -r dev-res dev-res-vanilla-water
cp -r stable-res stable-res-vanilla-water

sed -i -e '/gl_FragData\[0\] = applyFogAtDist(/a\      
    gl_FragData[0].w = 0.0;' stable-res/resources/shaders/compatibility/water.frag

sed -i -e '/gl_FragData\[0\] = applyFogAtDist(/a\      
    gl_FragData[0].w = 0.0;' stable-res/resources/shaders/compatibility/water.frag